import 'dart:convert';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;
import 'secure_storage_factory.dart';
class PremiumizeException implements Exception { const PremiumizeException(this.message); final String message; @override String toString()=>message; }
class PremiumizeService {
  PremiumizeService._(); static final instance=PremiumizeService._(); static const _base='https://www.premiumize.me/api',_tokenKey='orvix_premiumize_token_v1';
  final http.Client _client=http.Client(); final FlutterSecureStorage _storage=createOrvixSecureStorage();
  Future<String?> _token() async {final v=(await _storage.read(key:_tokenKey))?.trim();return v==null||v.isEmpty?null:v;} Future<bool> get isConnected async=>(await _token())!=null;
  Future<void> connectWithApiKey(String raw) async {final t=raw.trim();if(t.isEmpty)throw const PremiumizeException('Enter your Premiumize API key.');_json(await _client.get(Uri.parse('$_base/account/info'),headers:_headers(t)).timeout(const Duration(seconds:20)));await _storage.write(key:_tokenKey,value:t);}
  Future<Map<String,dynamic>> account() async {final t=await _require();final d=_json(await _client.get(Uri.parse('$_base/account/info'),headers:_headers(t)).timeout(const Duration(seconds:20)));return d is Map?Map<String,dynamic>.from(d):<String,dynamic>{};}
  Future<String> resolveMagnet(String magnet,{int? fileIndex,String? fileNameHint}) async {final t=await _require();final d=_json(await _client.post(Uri.parse('$_base/transfer/directdl'),headers:_formHeaders(t),body:{'src':_stripMetadata(magnet)}).timeout(const Duration(seconds:60)));final raw=d is Map?d['content']:null;final all=raw is List?raw.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():<Map<String,dynamic>>[];final videos=all.where((f)=>_video((f['path']??'').toString())).toList();if(videos.isEmpty)throw const PremiumizeException('Premiumize returned no playable video for this source.');Map<String,dynamic>? chosen;final h=fileNameHint?.trim().toLowerCase();if(h!=null&&h.isNotEmpty){for(final f in videos){if((f['path']??'').toString().toLowerCase().contains(h)){chosen=f;break;}}}if(chosen==null&&fileIndex!=null&&fileIndex>=0&&fileIndex<all.length&&_video((all[fileIndex]['path']??'').toString()))chosen=all[fileIndex];chosen??=(videos..sort((a,b)=>(int.tryParse(b['size']?.toString()??'')??0).compareTo(int.tryParse(a['size']?.toString()??'')??0))).first;final link=chosen['link']?.toString();if(link==null||link.isEmpty)throw const PremiumizeException('Premiumize did not return a direct stream link.');return link;}
  bool _video(String p)=>const ['.mkv','.mp4','.m4v','.avi','.mov','.webm','.ts','.m2ts'].any(p.toLowerCase().endsWith);Map<String,String> _headers(String t)=>{'Authorization':'Bearer $t','Accept':'application/json'};Map<String,String> _formHeaders(String t)=>{..._headers(t),'Content-Type':'application/x-www-form-urlencoded'};
  dynamic _json(http.Response r){dynamic d;try{d=jsonDecode(r.body);}catch(_){d=null;}final s=d is Map?d['status']?.toString():null;if(r.statusCode<200||r.statusCode>=300||s=='error'){final m=d is Map?(d['message']??d['error'])?.toString():null;throw PremiumizeException(m??'Premiumize request failed ('+r.statusCode.toString()+').');}return d;}
  Future<String> _require() async {final t=await _token();if(t==null)throw const PremiumizeException('Connect Premiumize first.');return t;}String _stripMetadata(String v){final i=v.indexOf('&orvix_');return i<0?v:v.substring(0,i);}Future<void> logout()=>_storage.delete(key:_tokenKey);void dispose()=>_client.close();
}