from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'Expected snippet not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')


# ---------------------------------------------------------------------------
# Source provider: local-only AIOStreams manifest + resolver integration.
# ---------------------------------------------------------------------------
replace_once(
    'lib/services/source_provider_service.dart',
    "  static const _torrentioKey = 'pikora_integrated_torrentio_url_v1';\n",
    "  static const _torrentioKey = 'pikora_integrated_torrentio_url_v1';\n"
    "  // AIOStreams manifest URLs can contain an encrypted profile credential.\n"
    "  // Keep the value local-only instead of putting it in cloud preferences.\n"
    "  static const _aioStreamsManifestKey = 'local_aiostreams_manifest_v1';\n",
)

replace_once(
    'lib/services/source_provider_service.dart',
    "    if (torrentio != null) {\n"
    "      final broad = _broadenTorrentioUrl(torrentio);\n"
    "      if (broad != null && broad != torrentio) out.add(broad);\n"
    "      out.add(torrentio);\n"
    "    }\n\n"
    "    for (final raw in prefs.getStringList(_prefsKey) ?? const <String>[]) {",
    "    if (torrentio != null) {\n"
    "      final broad = _broadenTorrentioUrl(torrentio);\n"
    "      if (broad != null && broad != torrentio) out.add(broad);\n"
    "      out.add(torrentio);\n"
    "    }\n\n"
    "    final aioStreams = _normalizeAddonUrl(\n"
    "      prefs.getString(_aioStreamsManifestKey) ?? '',\n"
    "    );\n"
    "    if (aioStreams != null && !out.contains(aioStreams)) {\n"
    "      out.add(aioStreams);\n"
    "    }\n\n"
    "    for (final raw in prefs.getStringList(_prefsKey) ?? const <String>[]) {",
)

replace_once(
    'lib/services/source_provider_service.dart',
    "  Future<SourceSortMode> getSortMode() async {",
    "  Future<String?> getAioStreamsManifestUrl() async {\n"
    "    final prefs = await SharedPreferences.getInstance();\n"
    "    return _normalizeAddonUrl(\n"
    "      prefs.getString(_aioStreamsManifestKey) ?? '',\n"
    "    );\n"
    "  }\n\n"
    "  Future<void> setAioStreamsManifestUrl(String raw) async {\n"
    "    final clean = raw.trim();\n"
    "    if (clean.isEmpty || !clean.toLowerCase().contains('/manifest.json')) {\n"
    "      throw const FormatException(\n"
    "        'Paste the full AIOStreams manifest URL generated by the instance.',\n"
    "      );\n"
    "    }\n"
    "    final normalized = _normalizeAddonUrl(clean);\n"
    "    if (normalized == null) {\n"
    "      throw const FormatException('Enter a valid HTTPS AIOStreams manifest URL.');\n"
    "    }\n"
    "    final uri = Uri.tryParse(clean);\n"
    "    if (uri == null || uri.scheme != 'https' || uri.host.isEmpty) {\n"
    "      throw const FormatException('AIOStreams manifest must use HTTPS.');\n"
    "    }\n"
    "    final prefs = await SharedPreferences.getInstance();\n"
    "    await prefs.setString(_aioStreamsManifestKey, normalized);\n"
    "  }\n\n"
    "  Future<void> clearAioStreamsManifestUrl() async {\n"
    "    final prefs = await SharedPreferences.getInstance();\n"
    "    await prefs.remove(_aioStreamsManifestKey);\n"
    "  }\n\n"
    "  Future<SourceSortMode> getSortMode() async {",
)

# ---------------------------------------------------------------------------
# Cloud sync: source addon/config URLs can contain credentials; never sync them.
# ---------------------------------------------------------------------------
replace_once(
    'lib/services/orvix_account_service.dart',
    "  static const _progressKey = 'pikora_continue_watching_v1';\n",
    "  static const _progressKey = 'pikora_continue_watching_v1';\n"
    "  static const _localOnlyPreferenceKeys = <String>{\n"
    "    'pikora_source_addons',\n"
    "    'pikora_integrated_torrentio_url_v1',\n"
    "  };\n",
)

replace_once(
    'lib/services/orvix_account_service.dart',
    "    final remotePreferences = _asMap(remote['preferences']);\n"
    "    await _restorePreferences(prefs, remotePreferences);",
    "    final remotePreferences = _asMap(remote['preferences'])\n"
    "      ..removeWhere((key, _) => _localOnlyPreferenceKeys.contains(key));\n"
    "    await _restorePreferences(prefs, remotePreferences);",
)

replace_once(
    'lib/services/orvix_account_service.dart',
    "      if (!key.startsWith('orvix_') && !key.startsWith('pikora_')) continue;\n"
    "      if (key == _watchlistKey || key == _libraryKey || key == _progressKey) continue;\n"
    "      final value = prefs.get(key);",
    "      if (!key.startsWith('orvix_') && !key.startsWith('pikora_')) continue;\n"
    "      if (key == _watchlistKey || key == _libraryKey || key == _progressKey) continue;\n"
    "      if (_localOnlyPreferenceKeys.contains(key)) continue;\n"
    "      final value = prefs.get(key);",
)

replace_once(
    'lib/services/orvix_account_service.dart',
    "      final key = entry.key;\n"
    "      if (!key.startsWith('orvix_') && !key.startsWith('pikora_')) continue;\n"
    "      if (prefs.containsKey(key)) continue;",
    "      final key = entry.key;\n"
    "      if (!key.startsWith('orvix_') && !key.startsWith('pikora_')) continue;\n"
    "      if (_localOnlyPreferenceKeys.contains(key)) continue;\n"
    "      if (prefs.containsKey(key)) continue;",
)

# ---------------------------------------------------------------------------
# Sources UI: first-class AIOStreams card with Midnight setup shortcut.
# ---------------------------------------------------------------------------
replace_once(
    'lib/screens/sources_screen.dart',
    "import 'package:flutter/material.dart';\n",
    "import 'package:flutter/material.dart';\n"
    "import 'package:url_launcher/url_launcher.dart';\n",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "  final _controller = TextEditingController();\n"
    "  final _preferredGroupsController = TextEditingController();\n",
    "  final _controller = TextEditingController();\n"
    "  final _aioStreamsController = TextEditingController();\n"
    "  final _preferredGroupsController = TextEditingController();\n",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "  String? _torrentioUrl;\n"
    "  bool _busy = true;",
    "  String? _torrentioUrl;\n"
    "  String? _aioStreamsUrl;\n"
    "  bool _busy = true;",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "    _controller.dispose();\n"
    "    _preferredGroupsController.dispose();",
    "    _controller.dispose();\n"
    "    _aioStreamsController.dispose();\n"
    "    _preferredGroupsController.dispose();",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "    final torrentio = await widget.sources.getIntegratedTorrentioUrl();\n"
    "    final show3D = await widget.sources.getShow3D();",
    "    final torrentio = await widget.sources.getIntegratedTorrentioUrl();\n"
    "    final aioStreams = await widget.sources.getAioStreamsManifestUrl();\n"
    "    final show3D = await widget.sources.getShow3D();",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "      _addons = values;\n"
    "      _priority = priority;\n"
    "      _torrentioUrl = torrentio;",
    "      _addons = values\n"
    "          .where((value) => value != aioStreams)\n"
    "          .toList(growable: false);\n"
    "      _priority = priority;\n"
    "      _torrentioUrl = torrentio;\n"
    "      _aioStreamsUrl = aioStreams;\n"
    "      _aioStreamsController.text = aioStreams == null\n"
    "          ? ''\n"
    "          : '$aioStreams/manifest.json';",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "  Future<void> _add() async {",
    "  Future<void> _saveAioStreams() async {\n"
    "    setState(() {\n"
    "      _busy = true;\n"
    "      _message = null;\n"
    "    });\n"
    "    try {\n"
    "      await widget.sources.setAioStreamsManifestUrl(_aioStreamsController.text);\n"
    "      await _reload();\n"
    "      if (mounted) {\n"
    "        setState(() => _message =\n"
    "            'AIOStreams connected. Its profile stays local on this device.');\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (!mounted) return;\n"
    "      setState(() {\n"
    "        _busy = false;\n"
    "        _message = e.toString();\n"
    "      });\n"
    "    }\n"
    "  }\n\n"
    "  Future<void> _clearAioStreams() async {\n"
    "    setState(() => _busy = true);\n"
    "    await widget.sources.clearAioStreamsManifestUrl();\n"
    "    _aioStreamsController.clear();\n"
    "    await _reload();\n"
    "    if (mounted) {\n"
    "      setState(() => _message = 'AIOStreams disconnected from Orvix.');\n"
    "    }\n"
    "  }\n\n"
    "  Future<void> _openMidnightAioStreamsSetup() async {\n"
    "    final uri = Uri.parse(\n"
    "      'https://aiostreamsfortheweebsstable.midnightignite.me/stremio/configure',\n"
    "    );\n"
    "    final opened = await launchUrl(uri, mode: LaunchMode.externalApplication);\n"
    "    if (!opened && mounted) {\n"
    "      setState(() => _message = 'Could not open the AIOStreams setup page.');\n"
    "    }\n"
    "  }\n\n"
    "  Future<void> _add() async {",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "        _engineCard(context),\n"
    "        const SizedBox(height: 18),\n"
    "        _sortCard(context),",
    "        _engineCard(context),\n"
    "        const SizedBox(height: 18),\n"
    "        _aioStreamsCard(context),\n"
    "        const SizedBox(height: 18),\n"
    "        _sortCard(context),",
)

replace_once(
    'lib/screens/sources_screen.dart',
    "  Widget _sortCard(BuildContext context) {",
    "  Widget _aioStreamsCard(BuildContext context) {\n"
    "    final color = Theme.of(context).colorScheme;\n"
    "    final active = _aioStreamsUrl != null;\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.all(22),\n"
    "      decoration: BoxDecoration(\n"
    "        color: const Color(0xFF0A0E0B),\n"
    "        borderRadius: BorderRadius.circular(22),\n"
    "        border: Border.all(\n"
    "          color: active\n"
    "              ? color.primary.withValues(alpha: .5)\n"
    "              : const Color(0xFF223125),\n"
    "        ),\n"
    "      ),\n"
    "      child: Column(\n"
    "        crossAxisAlignment: CrossAxisAlignment.start,\n"
    "        children: [\n"
    "          Row(\n"
    "            children: [\n"
    "              const Icon(Icons.stream_rounded),\n"
    "              const SizedBox(width: 10),\n"
    "              const Expanded(\n"
    "                child: Text(\n"
    "                  'AIOStreams',\n"
    "                  style: TextStyle(fontSize: 17, fontWeight: FontWeight.w900),\n"
    "                ),\n"
    "              ),\n"
    "              Container(\n"
    "                padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 4),\n"
    "                decoration: BoxDecoration(\n"
    "                  color: active\n"
    "                      ? const Color(0xFF173A2B)\n"
    "                      : const Color(0xFF34303A),\n"
    "                  borderRadius: BorderRadius.circular(999),\n"
    "                ),\n"
    "                child: Text(\n"
    "                  active ? 'ACTIVE' : 'OPTIONAL',\n"
    "                  style: TextStyle(\n"
    "                    fontSize: 10,\n"
    "                    fontWeight: FontWeight.w900,\n"
    "                    letterSpacing: .7,\n"
    "                    color: active\n"
    "                        ? const Color(0xFF83F0B8)\n"
    "                        : color.onSurfaceVariant,\n"
    "                  ),\n"
    "                ),\n"
    "              ),\n"
    "            ],\n"
    "          ),\n"
    "          const SizedBox(height: 8),\n"
    "          Text(\n"
    "            active\n"
    "                ? 'Orvix is querying your configured AIOStreams profile as an additional source aggregator.'\n"
    "                : 'Configure a public or self-hosted AIOStreams profile, then paste the generated manifest URL here.',\n"
    "            style: TextStyle(color: color.onSurfaceVariant, height: 1.4),\n"
    "          ),\n"
    "          const SizedBox(height: 7),\n"
    "          Text(\n"
    "            'Privacy: the manifest can act like a credential, so Orvix stores it only on this device and never cloud-syncs it.',\n"
    "            style: TextStyle(\n"
    "              color: color.onSurfaceVariant,\n"
    "              fontSize: 12.5,\n"
    "              height: 1.35,\n"
    "            ),\n"
    "          ),\n"
    "          const SizedBox(height: 14),\n"
    "          TextField(\n"
    "            controller: _aioStreamsController,\n"
    "            enabled: !_busy,\n"
    "            decoration: const InputDecoration(\n"
    "              labelText: 'AIOStreams manifest URL',\n"
    "              hintText: 'https://…/stremio/…/manifest.json',\n"
    "              prefixIcon: Icon(Icons.link_rounded),\n"
    "            ),\n"
    "          ),\n"
    "          const SizedBox(height: 12),\n"
    "          Wrap(\n"
    "            spacing: 10,\n"
    "            runSpacing: 10,\n"
    "            children: [\n"
    "              OutlinedButton.icon(\n"
    "                onPressed: _busy ? null : _openMidnightAioStreamsSetup,\n"
    "                icon: const Icon(Icons.open_in_new_rounded),\n"
    "                label: const Text('Open Midnight Stable setup'),\n"
    "              ),\n"
    "              FilledButton.icon(\n"
    "                onPressed: _busy ? null : _saveAioStreams,\n"
    "                icon: const Icon(Icons.save_outlined),\n"
    "                label: Text(active ? 'Update manifest' : 'Connect manifest'),\n"
    "              ),\n"
    "              if (active)\n"
    "                TextButton.icon(\n"
    "                  onPressed: _busy ? null : _clearAioStreams,\n"
    "                  icon: const Icon(Icons.link_off_rounded),\n"
    "                  label: const Text('Disconnect'),\n"
    "                ),\n"
    "            ],\n"
    "          ),\n"
    "        ],\n"
    "      ),\n"
    "    );\n"
    "  }\n\n"
    "  Widget _sortCard(BuildContext context) {",
)

# ---------------------------------------------------------------------------
# Details playback: Play auto-reuses a matching pinned source. Find Sources
# remains a manual chooser so the user can intentionally switch releases.
# ---------------------------------------------------------------------------
replace_once(
    'lib/screens/details_screen.dart',
    "      await _findSourcesAndPlay(item, episode: episode);\n"
    "    } catch (e) {\n"
    "      _showPlayError(e);\n"
    "    }\n"
    "  }\n\n"
    "  Future<void> _findSourcesAndPlay(\n"
    "    MediaItem item, {\n"
    "    EpisodeItem? episode,\n"
    "  }) async {",
    "      await _findSourcesAndPlay(\n"
    "        item,\n"
    "        episode: episode,\n"
    "        autoUsePinned: true,\n"
    "      );\n"
    "    } catch (e) {\n"
    "      _showPlayError(e);\n"
    "    }\n"
    "  }\n\n"
    "  Future<void> _findSourcesAndPlay(\n"
    "    MediaItem item, {\n"
    "    EpisodeItem? episode,\n"
    "    bool autoUsePinned = false,\n"
    "  }) async {",
)

replace_once(
    'lib/screens/details_screen.dart',
    "      final chosen = await _chooseSource(results, item, episode);\n"
    "      if (chosen == null || !mounted) return;\n"
    "      final cloud = await _chooseCloudProvider();",
    "      SourceResult? chosen;\n"
    "      if (autoUsePinned) {\n"
    "        final pinKey = widget.sources.sourceTargetKey(item, episode: episode);\n"
    "        final pinned = await widget.sources.getPinnedSourceIdentity(pinKey);\n"
    "        if (pinned != null && pinned.isNotEmpty) {\n"
    "          for (final result in results) {\n"
    "            if (widget.sources.matchesPinned(\n"
    "              result,\n"
    "              pinned,\n"
    "              seriesWide: item.kind == MediaKind.series,\n"
    "            )) {\n"
    "              chosen = result;\n"
    "              break;\n"
    "            }\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "      chosen ??= await _chooseSource(results, item, episode);\n"
    "      if (chosen == null || !mounted) return;\n"
    "      final cloud = await _chooseCloudProvider();",
)

print('Applied pinned continuity, AIOStreams, and local-only source credential patch.')
