const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let timer=null, selected=null, lastResults=[];
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function typeName(q){q=(q||'').toLowerCase();return q.includes('tv')||q.includes('series')?'TV series':q.includes('movie')||q.includes('feature')?'Movie':'Title'}
async function api(path,opt){const r=await fetch(path,opt);return r.json()}
async function status(){try{let s=await api('/api/status'); $('#acctState').textContent=s.connected?'Connected: '+s.user:'PikPak not connected'; $('#accountBtn').textContent=s.connected?'Connected ✓':'Sign in to PikPak';}catch{}}
function openLogin(){ $('#loginModal').style.display='flex'; $('#user').focus() }
$('#accountBtn').onclick=openLogin; $('#topAccount').onclick=openLogin; $('#closeLogin').onclick=()=>$('#loginModal').style.display='none';
$('#loginBtn').onclick=async()=>{let b=$('#loginBtn'); b.disabled=true; b.textContent='Signing in…'; $('#loginMsg').textContent='Preparing PikPak verification…'; let res=await api('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({Username:$('#user').value,Password:$('#pass').value})}); $('#loginMsg').textContent=res.message||''; if(res.need_verify&&res.verify_url){window.open(res.verify_url,'pikpakVerify','width=560,height=760'); b.textContent='Verification done — retry sign in';} else if(res.ok){$('#pass').value=''; $('#loginModal').style.display='none'; await status(); loadLibrary();} else b.textContent='Sign in'; b.disabled=false;}
$('#search').addEventListener('input',()=>{clearTimeout(timer);let q=$('#search').value.trim();if(q.length<2){$('#suggest').style.display='none';return}timer=setTimeout(()=>runSuggest(q),230)});
$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'&&lastResults[0]){choose(lastResults[0]);$('#suggest').style.display='none'}})
async function runSuggest(q){let box=$('#suggest');box.innerHTML='<div class="srow"><div></div><div class="muted">Searching…</div></div>';box.style.display='block';let r=await api('/api/search?q='+encodeURIComponent(q));if(!r.ok){box.innerHTML='<div class="srow"><div></div><div>'+esc(r.message)+'</div></div>';return}lastResults=r.results||[];if(!lastResults.length){box.innerHTML='<div class="srow"><div></div><div class="muted">No results</div></div>';return}box.innerHTML=lastResults.map((x,i)=>'<div class="srow" data-i="'+i+'">'+(x.i?.imageUrl?'<img src="'+esc(x.i.imageUrl)+'">':'<div></div>')+'<div><div class="stitle">'+esc(x.l)+'</div><div class="smeta">'+esc(typeName(x.qid))+(x.y?' • '+x.y:'')+'</div></div></div>').join('');box.querySelectorAll('.srow[data-i]').forEach(el=>el.onclick=()=>{choose(lastResults[+el.dataset.i]);box.style.display='none'})}
document.addEventListener('click',e=>{if(!e.target.closest('.searchWrap'))$('#suggest').style.display='none'})
function choose(x){selected=x; $('#detail').style.display='grid'; $('#dtitle').textContent=x.l||''; $('#dtype').textContent=typeName(x.qid).toUpperCase(); $('#dmeta').textContent=(x.y||'')+(x.id?' • '+x.id:''); $('#dstars').textContent=x.s||''; $('#dimg').src=x.i?.imageUrl||''; $('#matches').innerHTML=''; $('#findStatus').textContent=''; addRecent(x); $('#detail').scrollIntoView({behavior:'smooth',block:'center'})}
function recent(){try{return JSON.parse(localStorage.getItem('pikora.recent')||'[]')}catch{return[]}}
function addRecent(x){let a=recent().filter(v=>v.id!==x.id);a.unshift(x);a=a.slice(0,12);localStorage.setItem('pikora.recent',JSON.stringify(a));renderRecent()}
function renderRecent(){let a=recent(),g=$('#recentGrid');if(!a.length){g.innerHTML='<div class="muted">Search for a movie or TV series to get started.</div>';return}g.innerHTML=a.map((x,i)=>'<div class="card" data-r="'+i+'"><div class="poster">'+(x.i?.imageUrl?'<img src="'+esc(x.i.imageUrl)+'">':'No poster')+'</div><div class="ct"><b>'+esc(x.l)+'</b><small>'+esc(typeName(x.qid))+(x.y?' • '+x.y:'')+'</small></div></div>').join('');g.querySelectorAll('[data-r]').forEach(el=>el.onclick=()=>choose(a[+el.dataset.r]))}
$('#findBtn').onclick=async()=>{if(!selected)return;$('#findStatus').textContent='Scanning your PikPak library…';$('#matches').innerHTML='';let r=await api('/api/find?title='+encodeURIComponent(selected.l));if(!r.ok){$('#findStatus').textContent=r.message;return}let m=r.matches||[];$('#findStatus').textContent=m.length?m.length+' possible match(es) found.':'Not found in your PikPak library.';$('#matches').innerHTML=m.map(x=>'<div class="match"><div><b>'+esc(x.name)+'</b><div class="muted small">'+esc(x.mime_type||'cloud file')+'</div></div><button class="btn good" data-play="'+esc(x.id)+'">Play</button></div>').join('');$('#matches').querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(b.dataset.play))}
function watchlist(){try{return JSON.parse(localStorage.getItem('pikora.watch')||'[]')}catch{return[]}}
$('#watchBtn').onclick=()=>{if(!selected)return;let a=watchlist();if(!a.some(v=>v.id===selected.id)){a.unshift(selected);localStorage.setItem('pikora.watch',JSON.stringify(a));$('#watchBtn').textContent='✓ In watchlist'}}
async function play(id){let r=await api('/api/play?id='+encodeURIComponent(id));if(!r.ok){alert(r.message);return}if(r.url)window.open(r.url,'_blank');else alert('PikPak did not return a playable link for this file.')}
async function loadLibrary(){let box=$('#libList');box.innerHTML='<div class="muted">Loading PikPak…</div>';let r=await api('/api/library');if(!r.ok){box.innerHTML='<div class="muted">'+esc(r.message)+'</div>';return}let f=r.files||[];box.innerHTML=f.length?f.map(x=>'<div class="librow"><div><b>'+esc(x.name||'(unnamed)')+'</b><div class="muted tiny">'+(String(x.kind).includes('folder')?'Folder':esc(x.mime_type||'File'))+'</div></div>'+(String(x.kind).includes('folder')?'<span class="pill">folder</span>':'<button class="btn" data-play="'+esc(x.id)+'">Play</button>')+'</div>').join(''):'<div class="muted">Your PikPak root folder is empty.</div>';box.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(b.dataset.play))}
$('#refreshLib').onclick=loadLibrary;
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=b.dataset.view;if(v==='library'){$('#home').style.display='none';$('#library').style.display='block';loadLibrary()}else if(v==='watchlist'){$('#home').style.display='block';$('#library').style.display='none';let a=watchlist();localStorage.setItem('pikora.recent',JSON.stringify(a));renderRecent()}else{$('#home').style.display='block';$('#library').style.display='none';if(v==='search')$('#search').focus()}});
renderRecent();status();
