name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'ui/**'
      - 'go.mod'
      - '.github/workflows/build-windows.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Build Windows x64
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-H=windowsgui" -o Pikora-Windows-x64.exe .

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Pikora-Windows-x64
          path: Pikora-Windows-x64.exe
